# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - nvidia
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - jupyter
  - gymnasium
  - gymnasium-box2d
  - gymnasium-atari
  - gymnasium-classic_control
  - poetry>=1.3.0,<1.4.0
  - conda-lock
  - conda-forge::tensorflow-gpu=2.11.0

