[tool.poetry]
name = "tf-learning"
version = "0.1.0"
description = ""
authors = ["Anton Matosov <anton.matosov@gmail.com>"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
